# Default configuration for the Songbook Generator.
# This file can be overridden by environment variables.
# For example, to override the cover file_id, set the environment variable:
# SONGBOOK_COVER__FILE_ID="your_file_id"

[song_sheets]
folder_ids = [
    "1b_ZuZVOGgvkKVSUypkbRwBsXLVQGjl95",  # UT Song Sheets Google Docs
    "1bvrIMQXjAxepzn4Vx8wEjhk3eQS5a9BM",  # (3) Ready To Play
]

[cover]
file_id = "1HB1fUAY3uaARoHzSDh2TymfvNBvpKOEE221rubsjKoQ"

[toc]
columns_per_page = 2
column_width = 250
column_spacing = 20
margin_top = 20
margin_bottom = 20
margin_left = 25
margin_right = 25
title_height = 50
line_spacing = 12
text_font = "RobotoCondensed-Regular.ttf"
text_semibold_font = "RobotoCondensed-SemiBold.ttf"
text_fontsize = 10
title_font = "RobotoCondensed-Bold.ttf"
title_fontsize = 16
max_toc_entry_length = 60

[caching]
# If true, forces the use of GCS for caching. If false, forces local file system.
# If unset, GCS is used if both `gcs_worker_cache_bucket` and `gcp_region` are set.
# use_gcs =

[caching.gcs]
# The GCS bucket used for caching worker assets.
# Can be overridden by setting the `SONGBOOK_CACHING__GCS__WORKER_CACHE_BUCKET` environment variable.
# worker_cache_bucket = "songbook-generator-cache"
# The GCP region for the cache bucket.
# Can be overridden by setting the `SONGBOOK_CACHING__GCS__REGION` environment variable.
# region = "europe-west1"

[caching.local]
# The local directory where song sheets and other assets are cached.
# It can be overridden by setting the `SONGBOOK_CACHING__LOCAL__DIR` environment variable.
dir = "~/.cache/songbook-generator"
