# Default configuration for the Songbook Generator.
# This file is intended for overriding default settings.
# Default values are defined in `generator/common/config.py`.

[song_sheets]
# A list of Google Drive folder IDs to source song sheets from.
# folder_ids = []

[cover]
# The Google Drive file ID for the cover page template.
# file_id = ""

[toc]
# columns_per_page = 2
# column_width = 250
# column_spacing = 20
# margin_top = 20
# margin_bottom = 20
# margin_left = 25
# margin_right = 25
# title_height = 50
# line_spacing = 12
# text_font = "RobotoCondensed-Regular.ttf"
# page_number_font = "RobotoCondensed-SemiBold.ttf"
# text_fontsize = 10
# title_font = "RobotoCondensed-Bold.ttf"
# title_fontsize = 16
# max_toc_entry_length = 60

[caching]
# If true, forces the use of GCS for caching. If false, forces local file system.
# If unset, GCS is used if both `gcs_worker_cache_bucket` and `gcp_region` are set.
# use_gcs =

[caching.gcs]
# The GCS bucket used for caching worker assets.
# Can be overridden by setting the `SONGBOOK_CACHING__GCS__WORKER_CACHE_BUCKET` environment variable.
# worker_cache_bucket = "songbook-generator-cache"
# The GCP region for the cache bucket.
# Can be overridden by setting the `SONGBOOK_CACHING__GCS__REGION` environment variable.
# region = "europe-west1"

[caching.local]
# The local directory where song sheets and other assets are cached.
# It can be overridden by setting the `SONGBO-OK_CACHING__LOCAL__DIR` environment variable.
# dir = "~/.cache/songbook-generator"
