name: "Setup Songbook Generator Development Environment"
description: "Prepares the development environment for the Songbook Generator project"

steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.12'

  - name: Install uv
    uses: astral-sh/setup-uv@v5

  - name: Install the project
    run: uv sync --locked --all-extras --dev