name: 'Setup GCP and Dependencies'
description: 'Common setup for GCP authentication and project dependencies'

inputs:
  gcp_sa_key:
    description: 'GCP Service Account Key JSON'
    required: true
  gcp_project_id:
    description: 'GCP Project ID'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Load dotenv
      uses: falti/dotenv-action@v1.1.4
      with:
        path: .env
        log-variables: true
        export-variables: true
        keys-case: bypass

    - name: Auth Cloud SDK
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ inputs.gcp_sa_key }}
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '529.0.0'
        project_id: ${{ inputs.gcp_project_id }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      shell: bash
      run: uv sync --locked --all-extras --dev
