- id: "current"
  title: "Ukulele Tuesday - Current Songbook"
  description: >
    The current edition of the Ukulele Tuesday songbook,
    containing the songs used during our Tuesday sessions.

    We rotate the songs we play on Tuesday sessions frequently,
    so make sure to download the latest version!
  cover_file_id: "1VIAAD_IYEXSMch0rBcypDFzqWo50uRHl_TAfMmKCe80"
  preface_file_ids:
    - "1ZxYst-xswtkO6ZSU7tiPKKDoYwvBRWo-ag2tyu6fO2w"
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "regular"
  table_of_contents:
    # Include a pumpkin for songs tagged as `halloween`
    postfixes:
      - postfix: " 🎃"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "halloween"

- id: "complete"
  title: "Ukulele Tuesday - Complete Songbook"
  description: >
    The complete collection of all available Ukulele Tuesday songs sheets.
  cover_file_id: "19ZDP4wYJ9i650pdvc2P5wLrUEsfdYW7jMpr3yorIJRY"
  filters:
    - operator: "OR"
      filters:
        - key: "status"
          operator: "equals"
          value: "READY_TO_PLAY"
        - key: "status"
          operator: "equals"
          value: "APPROVED"
  table_of_contents:
    # Include a pumpkin for songs tagged as `halloween`
    postfixes:
      - postfix: " 🎃"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "halloween"
      - postfix: " 🎄"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "xmas"


- id: "ukulele-hooley-2025"
  title: "Ukulele Hooley 2025"
  description: "The official songbook for the 2025 Ukulele Hooley Friday jam."
  cover_file_id: "1jpZvqrpNF7HjX5_gpjH8FG8DLHKP63JjRU1gWbVpSg8"
  preface_file_ids:
    - "1cn7ZzJPD5g4IaPPfx5IJY0L9k7eboMwGV_KEnf4zdXs"
  table_of_contents:
    include_difficulty: false
    include_wip_marker: false
    columns_per_page: 1
    column_width: 360
    margin_left: 120
    margin_right: 120
    text_fontsize: 12
    line_spacing: 15
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "hooley-2025"
