- id: "current"
  title: "Ukulele Tuesday - Current Songbook"
  description: >
    The current edition of the Ukulele Tuesday songbook,
    containing the songs used during our Tuesday sessions.

    We rotate the songs we play on Tuesday sessions frequently,
    so make sure to download the latest version!
  cover_file_id: "1rxn4Kl6fe-SUFqfYieb5FrxkVwHLLVPbwOXtWRGc740"
  preface_file_ids:
    - "1ZxYst-xswtkO6ZSU7tiPKKDoYwvBRWo-ag2tyu6fO2w"
  table_of_contents:
    postfixes:
      - postfix: " ☘"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "ireland"
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "regular"

- id: "complete"
  title: "Ukulele Tuesday - Complete Songbook"
  description: >
    The complete collection of all available Ukulele Tuesday songs sheets.
  cover_file_id: "19ZDP4wYJ9i650pdvc2P5wLrUEsfdYW7jMpr3yorIJRY"
  filters:
    - operator: "OR"
      filters:
        - key: "status"
          operator: "equals"
          value: "READY_TO_PLAY"
        - key: "status"
          operator: "equals"
          value: "APPROVED"
  table_of_contents:
    # Include a pumpkin for songs tagged as `halloween`
    postfixes:
      - postfix: " 🎃"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "halloween"
      - postfix: " 🎄"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "xmas"
      - postfix: " ☘"
        filters:
          - key: "specialbooks"
            operator: "contains"
            value: "ireland"


- id: "wexford-2026"
  title: "Wexford 2026"
  description: "We packed a bunch of ukulele Tuesday classics in this songbook. Download it and play along with us at the Wexford uke fest Sunday jam!"
  cover_file_id: "1YOAi8XpZ-4clFLZwqHjHSrSnRfBDHBEjJoNIGOctXq4"
  preface_file_ids:
    # - "1cn7ZzJPD5g4IaPPfx5IJY0L9k7eboMwGV_KEnf4zdXs"
  table_of_contents:
    include_difficulty: false
    include_wip_marker: false
    columns_per_page: 1
    column_width: 360
    margin_left: 120
    margin_right: 120
    text_fontsize: 12
    line_spacing: 15
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "hooley-2025"

- id: "womens-in-regular"
  title: "Women Artists in Regular Songbook"
  description: >
    A collection of songs by female-identified artists
    that are currently included in the regular Ukulele Tuesday songbook.
  cover_file_id: null
  table_of_contents:
    postfixes: []
  filters:
    - operator: "AND"
      filters:
        - key: "gender"
          operator: "equals"
          value: "female"
        - key: "specialbooks"
          operator: "contains"
          value: "regular"

- id: "potential-new-womens-songs"
  title: "Potential New Women's Songs"
  description: >
    A collection of songs by female-identified artists,
    featuring songs NOT included in the regular Ukulele Tuesday songbook.
    This edition celebrates women in music and potential new additions to our repertoire!
  cover_file_id: null
  table_of_contents:
    postfixes: []
  filters:
    - operator: "AND"
      filters:
        - key: "gender"
          operator: "equals"
          value: "female"
        - key: "specialbooks"
          operator: "not_contains"
          value: "regular"
