- id: "regular"
  description: "The regular songbook, containing all standard songs."
  cover_file_id: "1rxn4Kl6fe-SUFqfYieb5FrxkVwHLLVPbwOXtWRGc740"
  preface_file_ids:
    - "1ZxYst-xswtkO6ZSU7tiPKKDoYwvBRWo-ag2tyu6fO2w"
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "regular"
