- id: "current"
  title: "Ukulele Tuesday - Current Songbook"
  description: >
    The current edition of the Ukulele Tuesday songbook,
    containing the songs used during our Tuesday sessions.

    We rotate the songs we play on Tuesday sessions frequently,
    so make sure to download the latest version!
  cover_file_id: "1rxn4Kl6fe-SUFqfYieb5FrxkVwHLLVPbwOXtWRGc740"
  preface_file_ids:
    - "1ZxYst-xswtkO6ZSU7tiPKKDoYwvBRWo-ag2tyu6fO2w"
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "regular"

- id: "complete"
  title: "Ukulele Tuesday - Complete Songbook"
  description: >
    The complete collection of all available Ukulele Tuesday songs sheets.
  cover_file_id: "19ZDP4wYJ9i650pdvc2P5wLrUEsfdYW7jMpr3yorIJRY"
  filters:
    - operator: "OR"
      filters:
        - key: "status"
          operator: "equals"
          value: "READY_TO_PLAY"
        - key: "status"
          operator: "equals"
          value: "APPROVED"

- id: "ukulele-hooley-2025"
  title: "Ukulele Hooley 2025"
  description: "The official songbook for the 2025 Ukulele Hooley festival."
  cover_file_id: "1s3SqDeRSJvKSuFBD5z3pwFmxgWcO0czK_MJ33VfDOAE"
  filters:
    - key: "specialbooks"
      operator: "contains"
      value: "hooley-2025"
