id: "complete"
title: "Ukulele Tuesday - Complete Songbook"
description: >
  The complete collection of all available Ukulele Tuesday songs sheets.
sections:
  cover:
    file_id: "19ZDP4wYJ9i650pdvc2P5wLrUEsfdYW7jMpr3yorIJRY"
  table_of_contents:
    # Include a pumpkin for songs tagged as `halloween`
    postfixes:
      - badges:
          - text: " 🎃"
        filters:
          - key: "theme"
            operator: "contains"
            value: "halloween"
      - badges:
          - text: " 🎄"
        filters:
          - key: "theme"
            operator: "contains"
            value: "christmas"
      - badges:
          - text: " ☘"
        filters:
          - key: "country"
            operator: "contains"
            value: "ireland"
  songs:
    filters:
      - operator: "OR"
        filters:
          - key: "status"
            operator: "equals"
            value: "READY_TO_PLAY"
          - key: "status"
            operator: "equals"
            value: "APPROVED"
