id: "current"
title: "Ukulele Tuesday - Current Songbook"
description: >
  The current edition of the Ukulele Tuesday songbook,
  containing the songs used during our Tuesday sessions.

  We rotate the songs we play on Tuesday sessions frequently,
  so make sure to download the latest version!
sections:
  cover:
    file_id: "1rxn4Kl6fe-SUFqfYieb5FrxkVwHLLVPbwOXtWRGc740"
  preface:
    file_ids:
      - "1ZxYst-xswtkO6ZSU7tiPKKDoYwvBRWo-ag2tyu6fO2w"
  table_of_contents:
    postfixes: []
    # postfixes:
    #   - postfix: " ☘"
    #     filters:
    #       - key: "specialbooks"
    #         operator: "contains"
    #         value: "ireland"
  songs:
    filters:
      - key: "name"
        operator: "in"
        value:
          - "9 to 5 - Dolly Parton"
          - "99 Luftballons - Nena"
          - "Accidentally in Love - Counting Crows"
          - "All These Things That I've Done - The Killers"
          - "All The Small Things - Blink-182"
          - "Angels - Robbie Williams"
          - "An Poc Ar Buile (The Mad Puck Goat) - The Chieftains"
          - "Baby One More Time - Britney Spears"
          - "Bad Moon Rising - Creedence Clearwater Revival"
          - "Basket Case - Green Day"
          - "Big Yellow Taxi - Joni Mitchell"
          - "BIRDS OF A FEATHER - Billie Eilish"
          - "Blinding Lights - The Weeknd"
          - "Blitzkrieg Bop - Ramones"
          - "Brown Eyed Girl - Van Morrison"
          - "Call Me - Blondie"
          - "Call Me Maybe - Carly Rae Jepsen"
          - "Candy - Paolo Nutini"
          - "C'est la Vie - B*Witched"
          - "Chaise Longue - Wet Leg"
          - "Chasing Cars - Snow Patrol"
          - "Cheap Thrills - Sia"
          - "Complicated - Avril Lavigne"
          - "Crazy World - Aslan"
          - "Creep - Radiohead"
          - "Dirty Old Town - The Pogues"
          - "Dog Days Are Over - Florence + The Machine"
          - "Don't Look Back In Anger - Oasis"
          - "Don't Stop Me Now - Queen"
          - "Don't You (Forget About Me) - Simple Minds"
          - "Dreams - The Cranberries"
          - "Everybody (Backstreet's Back) (Radio Edit) - Backstreet Boys"
          - "Ex's & Oh's - Elle King"
          - "Faith - George Michael"
          - "Flowers - Miley Cyrus"
          - "Folsom Prison Blues - Johnny Cash"
          - "Friday I'm In Love - The Cure"
          - "Fuck You - Cee Lo Green"
          - "Gangsta's Paradise - Coolio, L.V."
          - "Hand in My Pocket - Alanis Morissette"
          - "Hanno ucciso l'Uomo Ragno - 883"
          - "Happy Birthday To You (in D) - Traditional"
          - "Heroes (single version) - David Bowie"
          - "Highway to Hell - AC/DC"
          - "Ho Hey - The Lumineers"
          - "Holding Out for a Hero - Bonnie Tyler"
          - "Hotel California - The Eagles"
          - "Hotel Yorba - The White Stripes"
          - "Hot N Cold - Katy Perry"
          - "Hot Stuff (Single Version) - Donna Summer"
          - "House Of Gold - Twenty One Pilots"
          - "House of the Rising Sun - The Animals"
          - "I Kissed A Girl - Katy Perry"
          - "I Love It (feat. Charli XCX) - Icona Pop"
          - "Imagine - John Lennon"
          - "In Bloom - Nirvana"
          - "I Only Want To Be With You - Dusty Springfield"
          - "Island In The Sun - Weezer"
          - "I Will Survive - Gloria Gaynor"
          - "Jolene - Dolly Parton"
          - "Jump in the Line - Harry Belafonte"
          - "Just A Girl - No Doubt"
          - "Just Can't Get Enough - Depeche Mode"
          - "Karma Chameleon - Culture Club"
          - "Kids - MGMT"
          - "Kids in America - Kim Wilde"
          - "Kiss/Mustang Sally Medley - Prince/The Commitments"
          - "Lady Madonna - The Beatles"
          - "Learn to Fly - Foo Fighters"
          - "Linger - The Cranberries"
          - "Little Lion Man - Mumford and Sons"
          - "Livin' on a Prayer - Bon Jovi"
          - "Love Machine - Girls Aloud"
          - "Love Me Do - The Beatles"
          - "Man! I Feel Like A Woman! - Shania Twain"
          - "Material Girl - Madonna"
          - "Murder On The Dancefloor - Sophie Ellis-Bextor"
          - "Not Fair - Lily Allen"
          - "Nothing Compares 2 U - Sinéad O'Connor"
          - "One - U2"
          - "One Way or Another - Blondie"
          - "Paint it, Black - The Rolling Stones"
          - "Price Tag - Jessie J (feat. B.o.B)"
          - "Proud Mary - Tina Turner"
          - "Psycho Killer - Talking Heads"
          - "Red Wine Supernova - Chappell Roan"
          - "Respect - Aretha Franklin"
          - "Sarà Perché Ti Amo - Ricchi E Poveri"
          - "Set Fire to the Rain - Adele"
          - "Shake It Off - Taylor Swift"
          - "She Wolf - Shakira"
          - "Should I Stay or Should I Go - The Clash"
          - "Since U Been Gone - Kelly Clarkson"
          - "So What - P!nk"
          - "Space Oddity - David Bowie"
          - "Spice Up Your Life - Spice Girls"
          - "Stuck in the Middle with You - Stealers Wheel"
          - "Summer of '69 - Bryan Adams"
          - "Sweet Dreams (Are Made of This) - Eurythmics"
          - "Take A Chance On Me - ABBA"
          - "Take on Me - a-ha"
          - "Tarantella napoletana - Andrea Colombari"
          - "The Best (Edit) - Tina Turner"
          - "The Lion Sleeps Tonight - The Tokens"
          - "Torn - Natalie Imbruglia"
          - "Toxic - Britney Spears"
          - "Tree Hugger - Kimya Dawson & Antsy Pants"
          - "Valerie (feat. Amy Winehouse) (Version Revisited) - Mark Ronson"
          - "vampire - Olivia Rodrigo"
          - "Venus - Bananarama"
          - "Wake Up - Arcade Fire"
          - "Walking On Sunshine - Katrina & The Waves"
          - "Waterloo - ABBA"
          - "What's Up? - 4 Non Blondes"
          - "Where's Me Jumper? - Sultans Of Ping F.C."
          - "Whiskey in the Jar - Thin Lizzy"
          - "With Or Without You - U2"
          - "Wrecking Ball - Miley Cyrus"
          - "You're So Vain - Carly Simon"
          - "(You're the) Devil in Disguise - Elvis Presley"
          - "You're The One That I Want - John Travolta, Olivia Newton-John"
          - "You've Got The Love - Florence + The Machine"
          - "Zombie - The Cranberries"
