id: "wexford-2026"
title: "Wexford 2026"
description: "We packed a bunch of ukulele Tuesday classics in this songbook. Download it and play along with us at the Wexford uke fest Sunday jam!"
sections:
  cover:
    file_id: "1YOAi8XpZ-4clFLZwqHjHSrSnRfBDHBEjJoNIGOctXq4"
  preface:
    file_ids: []
    # file_ids:
    #   - "1cn7ZzJPD5g4IaPPfx5IJY0L9k7eboMwGV_KEnf4zdXs"
  table_of_contents:
    include_difficulty: false
    include_wip_marker: false
    columns_per_page: 1
    column_width: 360
    margin_left: 120
    margin_right: 120
    text_fontsize: 12
    line_spacing: 15
  songs:
    filters:
      - key: "specialbooks"
        operator: "contains"
        value: "hooley-2025"
