id: "wexford-2026"
title: "Wexford 2026"
description: "We packed a bunch of ukulele Tuesday classics in this songbook. Download it and play along with us at the Wexford uke fest Sunday jam!"
cover_file_id: "1YOAi8XpZ-4clFLZwqHjHSrSnRfBDHBEjJoNIGOctXq4"
sections:
  table_of_contents:
    include_difficulty: false
    include_wip_marker: false
    columns_per_page: 1
    column_width: 360
    margin_left: 120
    margin_right: 120
    text_fontsize: 12
    line_spacing: 15
  songs:
    filters:
      - key: "specialbooks"
        operator: "contains"
        value: "hooley-2025"
