name: API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run pre-commit hooks
      run: uvx --from 'pre-commit<5' pre-commit run --all-files --verbose
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Load dotenv
      uses: falti/dotenv-action@v1.1.4
      with:
        path: .env
        log-variables: true
        export-variables: true
        keys-case: bypass


    - name: Auth Cloud SDK
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '431.0.0'              # or latest
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Generate requirements.txt
      run: |
        uv export --no-emit-project --format requirements-txt > api/requirements.txt
        cat api/requirements.txt

    - name: Compute function name
      id: fn-name
      run: |
        BASE_FN=${{ env.API_FUNCTION_NAME }}
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "name=${BASE_FN}-pr-${{ github.event.pull_request.number }}" >>"$GITHUB_OUTPUT"
        else
          echo "name=${BASE_FN}" >>"$GITHUB_OUTPUT"
        fi

    - name: Deploy to Cloud Functions
      id: deploy
      run: |
        gcloud functions deploy "${{ steps.fn-name.outputs.name }}" \
          --gen2 \
          --region=${{ env.GCP_REGION }} \
          --runtime=python312 \
          --trigger-http \
          --source=api \
          --entry-point=main \
          --allow-unauthenticated \
          --set-env-vars=\
        GOOGLE_CLOUD_PROJECT=${{ env.GCP_PROJECT_ID }},\
        GCP_REGION=${{ env.GCP_REGION }},\
        PUBSUB_TOPIC=${{ env.PUBSUB_TOPIC }},\
        FIRESTORE_COLLECTION=${{ env.FIRESTORE_COLLECTION }},\
        GCS_CDN_BUCKET=${{ env.GCS_CDN_BUCKET }},\
        JOB_TTL_DAYS=3,\
        LOG_LEVEL=info
        
        # Output the function URL for PR comments
        FUNCTION_URL=$(gcloud functions describe "${{ steps.fn-name.outputs.name }}" --region="${{ env.GCP_REGION }}" --format="value(serviceConfig.uri)")
        echo "function_url=$FUNCTION_URL" >> "$GITHUB_OUTPUT"

    - name: Update PR preview status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          const functionUrl = `${{ steps.deploy.outputs.function_url }}`;
          const functionName = `${{ steps.fn-name.outputs.name }}`;
          
          // Find existing preview comment
          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
          });
          
          const existingComment = comments.data.find(
            comment => comment.body.includes('## 🚀 Preview Deployments')
          );
          
          let commentBody;
          if (existingComment) {
            // Update existing comment to mark API as deployed
            let body = existingComment.body;
            body = body.replace(/- \[ \] API:.*/, `- [x] API: [${functionUrl}](${functionUrl})`);
            commentBody = body;
          } else {
            // Create new comment with API status
            commentBody = `## 🚀 Preview Deployments

          - [x] API: [${functionUrl}](${functionUrl})
          - [ ] Generator Worker: ⏳ Deploying...
          - [ ] UI: ⏳ Deploying...
          
          _Preview deployments will be automatically cleaned up when the PR is merged or closed._`;
          }
          
          if (existingComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existingComment.id,
              body: commentBody
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
          }
