name: Test & Deploy Cloud Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run pre-commit hooks
      run: uvx --from 'pre-commit<5' pre-commit run --all-files --verbose
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run on main for now so we keep it working
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Auth Cloud SDK
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '431.0.0'              # or latest
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Generate requirements.txt
      run: |
        uv export --no-emit-project --format requirements-txt > generator/requirements.txt
        cat generator/requirements.txt

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy ${{ vars.GCP_FUNCTION_NAME }} \
          --gen2 \
          --region=${{ vars.GCP_REGION }} \
          --runtime=python312 \
          --trigger-http \
          --source=generator \
          --entry-point=main \
          --memory=1Gi \
          --allow-unauthenticated
