name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run pre-commit hooks
      run: uvx --from 'pre-commit<5' pre-commit run --all-files --verbose
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '431.0.0'              # or latest
        project_id: ${{ vars.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Generate requirements.txt
      run: uv export --format requirements-txt > src/songbook_generator/requirements.txt

    - name: Deploy to Cloud Functions
      working-directory: ./src/songbook_generator
      run: |
        gcloud functions deploy ${{ vars.GCP_FUNCTION_NAME }} \
          --region=${{ vars.GCP_REGION }} \
          --runtime=python312 \
          --trigger-http \
          --source=function \
          --entry-point=main \
          --allow-unauthenticated
