name: Deploy GCS Infrastructure

on:
  workflow_dispatch:
    inputs:
      force_recreate:
        description: 'Force recreate resources (use with caution)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy GCS Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Load environment variables
      uses: falti/dotenv-action@v1.1.4
      with:
        path: .env
        export-variables: true
        keys-case: bypass
    
    - name: Auth Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
    
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        version: '431.0.0'
    
    - name: Make deploy script executable
      run: chmod +x ./deploy-gcs.sh
    
    - name: Run GCS deployment script
      run: ./deploy-gcs.sh
      env:
        FORCE_RECREATE: ${{ github.event.inputs.force_recreate }}
    
    - name: Deployment completed
      run: |
        echo "✅ Infrastructure deployment completed successfully!"
        echo "The following resources have been set up:"
        echo "- Pub/Sub topic: ${{ env.PUBSUB_TOPIC }}"
        echo "- Firestore collection: ${{ env.FIRESTORE_COLLECTION }}"
        echo "- GCS CDN bucket: ${{ env.GCS_CDN_BUCKET }}"
        echo "- GCS worker cache bucket: ${{ env.GCS_WORKER_CACHE_BUCKET }}"
