name: Deploy GCS Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_call:
  workflow_dispatch:
    inputs:
      force_recreate:
        description: 'Force recreate resources (use with caution)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy GCS Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Load environment variables
      uses: falti/dotenv-action@v1.1.4
      with:
        path: .env
        export-variables: true
        keys-case: bypass

    - name: Override environment variables for PR environment
      if: github.event_name == 'pull_request'
      run: |
        PR_NUM="${{ github.event.pull_request.number }}"
        echo "Setting up PR-specific environment variables for PR #${PR_NUM}"

        # Override environment variables for PR environment
        echo "PUBSUB_TOPIC=${{ env.PUBSUB_TOPIC }}-pr-${PR_NUM}" >> $GITHUB_ENV

        echo "PR environment variables set:"
        echo "- PUBSUB_TOPIC: ${{ env.PUBSUB_TOPIC }}-pr-${PR_NUM}"

    - name: Auth Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}
        version: '431.0.0'

    - name: Create Pub/Sub topic
      run: |
        echo "Creating Pub/Sub topic ${PUBSUB_TOPIC}…"
        gcloud pubsub topics create "${PUBSUB_TOPIC}" \
          --project="${{ env.GCP_PROJECT_ID }}" || echo "Topic may already exist, continuing…"

    - name: Deployment completed
      run: |
        echo "✅ Infrastructure deployment completed successfully!"
        echo "The following resources have been set up:"
        echo "- Pub/Sub topic: ${{ env.PUBSUB_TOPIC }}"

        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo ""
          echo "🔧 PR-specific resources created for PR #${{ github.event.pull_request.number }}"
          echo "These resources will need to be cleaned up when the PR is closed."
        fi
