name: Force Cache Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'main'
        type: choice
        options:
        - main

jobs:
  force-sync:
    name: Force GCS Cache Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup GCP and dependencies
      uses: ./.github/actions/setup-gcp-deps
      with:
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
        gcp_project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Publish force sync message
      run: |
        CACHE_REFRESH_PUBSUB_TOPIC="${{ env.CACHE_REFRESH_PUBSUB_TOPIC }}"
        echo "Publishing force sync message to ${CACHE_REFRESH_PUBSUB_TOPIC}"
        gcloud pubsub topics publish "$CACHE_REFRESH_PUBSUB_TOPIC" \
          --message="Forcing cache sync and merge" \
          --attribute="force=true"
