name: Trigger Sync

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'main'
        type: choice
        options:
        - main
      force:
        description: 'Force a full cache sync, ignoring timestamps'
        required: false
        default: false
        type: boolean

jobs:
  trigger-sync:
    name: Trigger GCS Cache Sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup GCP and dependencies
      uses: ./.github/actions/setup-gcp-deps
      with:
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
        gcp_project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Publish sync message
      run: |
        CACHE_REFRESH_PUBSUB_TOPIC="${{ env.CACHE_REFRESH_PUBSUB_TOPIC }}"
        echo "Publishing sync message to ${CACHE_REFRESH_PUBSUB_TOPIC} with force=${{ github.event.inputs.force }}"
        gcloud pubsub topics publish "$CACHE_REFRESH_PUBSUB_TOPIC" \
          --message="Triggering cache sync and merge" \
          --attribute="force=${{ github.event.inputs.force }}"
